services:
  mysql:
    image: mysql:8.0
    container_name: docker-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: userdb
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql